packages:
  - .

ignoredBuiltDependencies:
  - '@scarf/scarf'
  - '@tree-sitter-grammars/tree-sitter-yaml'
  - core-js-pure
  - tree-sitter
  - tree-sitter-json
  - unrs-resolver

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
