from sero import consts


PROJECT_VERSION = "1.0"
PATH_TO_SOURCEDIR = "./docs"
PATH_TO_OUTDIR = "./output"
PATH_TO_DBFILE = "./sero.duckdb"
ANCHOR_BORDER = consts.ANCHOR_BORDER_CHOICES[0]
ANCHOR_GAP = 0
ID_MARKER_HEADER = "ref_id"
ID_MARKER_POS = [10, 16]
ID_MARKER_SIZE = 9
ID_MARKER_COLOR = "#ff3c2e"
TEST_ACTION = consts.TEST_ACTION_CHOICES[0]
RETRIEVE_ACTION = consts.RETRIEVE_ACTION_CHOICES[0]