name: Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Install dependencies
      run: uv sync --all-groups

    - name: Run tests
      env:
        SERO_SECURITY__SECRET_KEY: ci-test-secret-key
        SERO_DB__FILEPATH: ${{ runner.temp }}/sero.sqlite
        SERO_LOG__FILEPATH: ${{ runner.temp }}/sero_logs/app.jsonl
        SERO_PROCESSING__DIRPATH: ${{ runner.temp }}/sero_output
      run: uv run pytest

    - name: Python Semantic Release
      id: release
      uses: python-semantic-release/python-semantic-release@v9.15.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        root_options: "--strict --verbose"
        
    # - name: Build package
    #   if: steps.release.outputs.released == 'true'
    #   run: uv build

    # - name: Publish to PyPI
    #   if: steps.release.outputs.released == 'true'
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     # Uncomment when you're ready to publish to PyPI
    #     # password: ${{ secrets.PYPI_API_TOKEN }}
    #     repository-url: https://test.pypi.org/legacy/  # Test PyPI for now
    #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
