name: Release

on:
  workflow_run:
    workflows: ["CI"]
    branches: [ main ]
    types: [ completed ]

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    concurrency: release
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      id: semrel
      uses: python-semantic-release/python-semantic-release@v9.15.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        root_options: "--strict --verbose"

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/sero:latest
          ghcr.io/${{ github.repository_owner }}/sero:${{ github.sha }}

    - name: Publish GitHub Release artifacts (optional)
      if: ${{ steps.semrel.outputs.released == 'true' }}
      run: echo "Release created by semantic-release."

    - name: Summary
      run: |
        echo "Release workflow completed. CI passed, semantic-release evaluated commits, and Docker image pushed to GHCR."

    - name: Determine if release is needed
      id: check_release
      shell: bash
      run: |
        git fetch --tags --quiet
        LAST_TAG=$(git describe --tags --abbrev=0 || true)
        if [ -n "$LAST_TAG" ]; then
          RANGE="$LAST_TAG..HEAD"
        else
          RANGE="HEAD"
        fi
        echo "Using range: $RANGE"
        MESSAGES=$(git log --format=%s $RANGE || true)
        echo "$MESSAGES" | sed 's/^/  - /'
        if echo "$MESSAGES" | grep -E '(^feat(\!|:)|^fix:|^perf:|BREAKING CHANGE:)' -q; then
          echo "should_release=true" >> "$GITHUB_OUTPUT"
        else
          echo "should_release=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Python Semantic Release
      if: steps.check_release.outputs.should_release == 'true'
      id: release
      uses: python-semantic-release/python-semantic-release@v9.15.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        root_options: "--strict --verbose"
        
    # - name: Build package
    #   if: steps.release.outputs.released == 'true'
    #   run: uv build

    # - name: Publish to PyPI
    #   if: steps.release.outputs.released == 'true'
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     # Uncomment when you're ready to publish to PyPI
    #     # password: ${{ secrets.PYPI_API_TOKEN }}
    #     repository-url: https://test.pypi.org/legacy/  # Test PyPI for now
    #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
