name: Release

on:
  workflow_run:
    workflows: ["CI"]
    branches: [ main ]
    types: [ completed ]

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    concurrency: release
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      id: semrel
      uses: python-semantic-release/python-semantic-release@v9.15.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        root_options: "--strict --verbose"

    # Build frontend and package backend+static as a release asset (sdist-like archive)
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Install frontend dependencies
      working-directory: frontend
      run: pnpm install --frozen-lockfile

    - name: Build frontend
      working-directory: frontend
      run: pnpm build

    - name: Sync frontend build into backend static
      run: |
        rm -rf backend/src/static && mkdir -p backend/src/static
        cp -r frontend/dist/* backend/src/static/

    - name: Package backend with static asset
      run: tar czf sero-backend-with-static.tar.gz backend

    - name: Upload asset to GitHub Release
      if: ${{ steps.semrel.outputs.released == 'true' }}
      uses: softprops/action-gh-release@v2
      with:
        files: |
          sero-backend-with-static.tar.gz
        fail_on_unmatched_files: true

    - name: Login to GHCR
      if: ${{ steps.semrel.outputs.released == 'true' }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Prepare image tags (lowercase owner)
      if: ${{ steps.semrel.outputs.released == 'true' }}
      id: prep
      run: |
        echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_ENV"
        echo "REPO_LC=${GITHUB_REPOSITORY#*/}" >> "$GITHUB_ENV"

    - name: Build and push Docker image
      if: ${{ steps.semrel.outputs.released == 'true' }}
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}:latest
          ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}:${{ github.sha }}

    - name: Publish GitHub Release artifacts (optional)
      if: ${{ steps.semrel.outputs.released == 'true' }}
      run: echo "Release created by semantic-release."

    - name: Summary
      run: |
        echo "Release workflow completed. CI passed, semantic-release evaluated commits, and Docker image pushed to GHCR."

